name: Build EA8300 ImmortalWrt Passwall2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev \
          libssl-dev python3 python3-pip rsync unzip zlib1g-dev wget

      - name: Clone ImmortalWrt
        run: |
          git clone --depth=1 https://github.com/immortalwrt/immortalwrt.git source

      - name: Copy configuration
        run: |
          cp config.seed source/.config
          cp -r files/* source/files/

      - name: Update feeds
        run: |
          cd source
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          cd source
          make defconfig

      - name: Build
        run: |
          cd source
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: EA8300-firmware
          path: source/bin/targets/ipq40xx/generic/*
